import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class AppConstants {
    public USERCATEGRORY_USER = "USER";
    public USERCATEGRORY_GROUP = "GROUP";
    public USERCATEGRORY_LEGISLATURE = "LEGISLATURE";
    public USERCATEGRORY_EXECUTIVE = "EXECUTIVE";
    public USERCATEGRORY_LEGISLATIVE_DISTRICT = "LEGISLATIVE DISTRICT";
    public USERCATEGRORY_POLITICAL_PARTY = "POLITICAL PARTY";
    public USERCATEGRORY_LEGISLATIVE_COMMITTEE = "LEGISLATIVE COMMITTEE";    
    public USERCATEGRORY_MUNICIPALITIES = "MUNICIPALITIES";
    public USERCATEGRORY_BILL = "BILL";
}